export const industryTypes = [
  "Accounting",
  "Administration & Office Support",
  "Advertising, Arts & Media",
  "Banking & Financial Services",
  "Call Centre & Customer Service",
  "CEO & General Management",
  "Community Services & Development",
  "Construction",
  "Consulting & Strategy",
  "Design & Architecture",
  "Education & Training",
  "Engineering",
  "Farming, Animals & Conservation",
  "Healthcare & Medical",
  "Hospitality & Tourism",
  "Information & Communication Technology",
  "Marketing & Communications",
  "Real Estate & Property",
  "Sales",
  "Science & Technology",
  "Trades & Services",
];
