FROM node:22-alpine AS base

# System dependencies
RUN apk add --no-cache libc6-compat openssl

WORKDIR /app

# Environment Args
ARG NEXT_PUBLIC_API_BASE_URL
ARG POSTGRES_URL
ARG POSTGRES_URL_NON_POOLING
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG CLERK_SECRET_KEY
ARG NEXT_PUBLIC_CLERK_SIGN_UP_URL
ARG NEXT_PUBLIC_CLERK_SIGN_IN_URL
ARG NEXT_CLERK_SIGN_UP_FALLBACK_URL
ARG NEXT_CLERK_SIGN_IN_FALLBACK_URL
# Set Envs for the build process
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV POSTGRES_URL=$POSTGRES_URL
ENV POSTGRES_URL_NON_POOLING=$POSTGRES_URL_NON_POOLING
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV CLERK_SECRET_KEY=$CLERK_SECRET_KEY
ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_SIGN_UP_URL
ENV NEXT_PUBLIC_CLERK_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_SIGN_IN_URL
ENV NEXT_CLERK_SIGN_UP_FALLBACK_URL=$NEXT_CLERK_SIGN_UP_FALLBACK_URL
ENV NEXT_CLERK_SIGN_IN_FALLBACK_URL=$NEXT_CLERK_SIGN_IN_FALLBACK_URL

# Install dependencies without running scripts (prevents prisma crash)
COPY package.json package-lock.json ./
RUN npm cache clean --force && npm install --frozen-lockfile --ignore-scripts

# 4. Copy Prisma schema and generate client manually
COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]